services:
  web:
    build:
      context: .
    ports:
      - "3001:3001"
    tty: true
    volumes:
      - ./project:/app
      # - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    # backend作成までコメントアウト
    # networks:
    #   - restaurant-sales-backend_back
# volumes:
#   node_modules:
# backend作成までコメントアウト
# networks:
#   restaurant-sales-backend_back:
#     external: true
