services:
  web:
    build:
      context: .
    ports:
      - "3001:3001"
    tty: true
    volumes:
      - ./project:/app
    command: sh -c "npm run dev"
    networks:
      - backend_back

networks:
  backend_back:
    external: true
